---
#################################
#Playbook de instalacao do nginx#
#################################
- name: Instalacao do nginx
  hosts: teste
  remote_user: "{{ user }}"
  tasks:
    - name: Instalando o nginx e garantindo que o nginx esteja na versão mais recente!
      apt: name=nginx sate=latest
      notify:
        - start nginx
  #Garantindo que o nginx esteja rodando e ative durante o boot do sistema!
  handlers:
     - name: start nginx
       service: name=nginx state=started enabled=yes
       tags: install-nginx

