---
#Playbook para criacao do usuario do nginx
- name: Criacao do usuario para start do nginx
  hosts: teste
  vars:
    - username: nginxuser
  tasks:
    - name: Criando usuario nos servidores.
      user: name={{ username }} shell=/bin/bash createhome=yes state=present
      tags: usuario_nginx
