    - name: 'Download fucked press'
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/latest.tar.gz

    - name: 'Descompacta wordpress pro negocim la da web'
      unarchive:
        src: /tmp/latest.tar.gz
        dest: /var/www/
        remote_src: yes
      become: yes
    - name: 'Copia arquivos'
      copy:
        src: /var/www/wordpress/wp-config-sample.php
        dest: /var/www/wordpress/wp-config.php
        remote_src: yes
      become: yes
    
    - name: 'Configura o wp-config com as entradas do banco de dados' 
      replace:
        path: /var/www/wordpress/wp-config.php
        regexp: '{{ item.regex }}'
        replace: '{{ item.value }}'
        backup: yes
      with_items:
        - { regex: 'database_name_here', value: "{{ wp_db_name }}" }
        - { regex : 'username_here', value: "{{ wp_username }}" }
        - { regex : 'password_here', value: "{{ wp_user_password }}" }
        - { regex : 'localhost', value: "{{ db_host_ip }}" }
      become: yes