    - name: 'instala pacotes'
      apt:
        name: "{{ packages }}"
        state: latest
      become: yes
      vars:
        packages: 
          - mysql-server
          - python-mysqldb

    - name: 'Cria o banco Mysql'
      mysql_db:
        name: "{{ wp_db_name }}"
        login_user: "root"
        login_password: "_HiStOrY_V2_"
        state: present
      become: yes

    - name: 'cria um usuário'
      mysql_user:
        name: "{{ wp_username }}"
        password: "{{ wp_user_password }}"
        priv: "{{ wp_db_name }}.*:ALL"
        state: present
        host: "{{ wp_host_ip }}"
      become: yes

    - name: 'altera arquivos mysql' 
      replace:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '{{ item.regex }}'
        replace: '{{ item.value }}'
        backup: yes
      loop:
        - { regex: '127.0.0.1', value: '0.0.0.0' }
      become: yes
      notify: 'restart mysql'
